### ISSUE TITLE
Specifications for API reporting

### ISSUE THREAD

**Issue by maxpearl** [OpenTechFund/bypass-otf_proxy#65]
JSON request and response.

**Comment by maxpearl** [comment]
Committed modifications to the [specifications](https://github.com/OpenTechFund/bypass-otf_proxy/blob/master/bcapp/flaskapp/json_report.json) (I'd forgotten we'd added this to the repo already) and [some new docs](https://github.com/OpenTechFund/bypass-otf_proxy/blob/master/bcapp/flaskapp/README.md) to this repo. @jheretic have a looksee. Let me know if there's anything amiss.

**Comment by jheretic** [comment]
@maxpearl this looks great! The only thing I'd add right now is an indication in the spec of which (if any) parameters are required vs optional. If `failure_detail` is being used to indicate non-HTTP errors, then probably `domain_status` and `domain_content` at least should be optional?

**Comment by maxpearl** [comment]
Thanks, this is helpful. I've added required and optional fields. I'm assuming two kinds of reports - automated which will send the domain http status and such, and manual, which won't.
